# Generated by Django 4.1.2 on 2022-10-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
