# Generated by Django 4.1.2 on 2022-10-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_game_options_rename_title_game_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='title',
        ),
    ]
