# Generated by Django 4.1.2 on 2022-10-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_game_options_rename_name_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(default='Darion', max_length=250),
        ),
        migrations.AddField(
            model_name='game',
            name='game_url',
            field=models.CharField(default='Darion', max_length=250),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='Darion', max_length=250),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(default='Darion', max_length=250),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(default='Darion', max_length=250),
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.CharField(default='Darion', max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='Darion', max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.CharField(default='Darion', max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(default='Darion', max_length=100),
        ),
    ]
