# Generated by Django 4.1.2 on 2022-10-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_game_description_alter_game_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_url',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
