# Generated by Django 4.1.2 on 2022-10-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_game_description_alter_game_developer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('games', models.ManyToManyField(to='main_app.game')),
            ],
        ),
    ]
